### PR TITLE
Adds improved denominator support for claiming rewards and tests

### PR DESCRIPTION
**Pull request by dshaw002**
This solution fixes the refresh/claim issue with denominators > 1.

Basically, every time someone refreshes the farmer, the system takes the current time, evaluates how many rewards have been accrued and then updates the last_updated_ts to the current time or end of reward (whichever comes first). 

This is fine when the denominator is default. However, when the denominator is > 1 (e.g. 10), and someone refreshes before the denominator is reached, the farmer will receive 0 awards and the updated_ts will still the current time, losing the opportunity time between their last_updated_ts and now_ts.

This solution calculates an offset from the denominator with the current time and uses that as a way to round down the now_ts to the nearest previous interval. This ensures the farmer gets the maximum reward available to them, but sets the last_updated_ts to the exact time they receive their last reward (if they can receive rewards yet).

Staking Denominator Fix Explanation

### CODE REVIEW

**Comment by ilmoi** [comment]
Thanks for the reply!

Hm I'm not sure I understand the proposed solution. If you think it addresses my points then feel free to throw together the rust code and I'll take a look (you can add tests later, after we agree it works).

Keep in mind that you need to change the state _consistently_. This means we can't have now_ts be X in one place and Y in another place. It needs to be the same across all downstream function calls. So whatever change you make has to happen at the top-most level, where now_ts is beging calculated currently.

**Comment by dshaw002** [comment]
1. I updated the latest commit to add a new lower_bound variable. This takes the max of begin_schedule_ts or begin_staking_ts to not include pre-reward time for a staker
2. I'm only including capped_now_ts when it comes to calculating fixed rate rewards. I localized it to be used when it's only relevant to not have downstread effects on state
3. See #2. In this update I'm more focused on where I'm updating now_ts and I'm creating a new variable for it. This should prevent inconsistent state issues
4. I believe the newly_accrued_reward function already does this in FarmerFixedRateReward (https://github.com/gemworks/gem-farm/blob/main/programs/gem_farm/src/state/farmer.rs#L256)

Let me know if this approach is better. In order for the denominator fix to work you do have to adjust the last_updated_time in the reward to be the offset time (see #4). I didn't do any other changes for re-enroll (so if you go up tiers or re-enroll in between intervals, you will see the in-between time), so I wonder if that' s necessary for smoothly re-enrolling someone. Otherwise, they move any rewards in-between intervals when they graduate (though I might not fully grok the re-enroll logic).

**Comment by ilmoi** [comment]
Hm I must be not understanding something, but I'm not sure how this solves the issue.

Here's what I think you're doing:
1. you're reducing `now_ts` and `reward_upper_bound` alongside with it just enough that when divided by `denominator` it doesn't have a remainder
2. but it still produces same quotient
3. which means this doesn't change
```rs
        rarity_points
            .try_mul(per_rarity_point)?
            .try_div(self.denominator)
```
4. which means the paid out rewards don't change
5. so... what does actually change then? 

What I think you want (might be wrong) - is to reduce `now_ts` stored on farmer on update N so that when re-run on update N+1 it starts calculating rewards from that reduced now_ts (which becomes`last_updated_ts`). Which means the line you really wanna affect is this:
```rs
# on Farmer struct
self.fixed_rate.last_updated_ts = self.fixed_rate.reward_upper_bound(now_ts)?;
```

But to affect that line you need to affect the entire state. Goes back to point (3) above. There is no way around it.

**Comment by dshaw002** [comment]
What changes is the last_updated_time (which is what really matters). There are two problems with the current implementation:

1. I refresh_farmer too earlier. Quotient is 0, but last_updated_time is updated to now_ts. This causes

**Comment by dshaw002** [comment]
I would effect last_updated_ts in the situation that we have a fixed reward where the denominator is > 1. I don't change now_ts in any way with this update. It's localized to this function and this variable. This could have implications maybe on future calculations (because of the modified last_updated_ts), but it's the only way the denominator bug can be fixed (unless we add an extra struct variable that keeps internal track of when the last real reward time was).

Some more context below:

--

What changes is the last_updated_time (which is what really matters). There are two problems with the current implementation:

1. I refresh_farmer too earlier. Quotient is 0, but last_updated_time is updated to now_ts. This invalidates all of my work from the previous last_updated_ts to now_ts
2. I refresh_farmer after my reward. Quotient is whatever reward I should get, but last_updated_time is updated to now_ts. This invalidates all of my work from the time I got my last reward to now_ts.

This main solution involves rounding down the last_updated_ts to the time of the last eligible reward in order to not remove any unrealized reward time. Otherwise a staker could invalidate their rewards by accident or a malicious actor could keep refreshing rewards and updating the last_updated_ts to now_ts and prevent any staker from realizing rewards.

--

Let me know if this explanation helps. I could also show a demo video showing how it works and what the issue is. Maybe that makes things more clear?

**Comment by dshaw002** [comment]
I simplified the farmer.rs code. I also updated the tests to check for lastUpdatedTs. Let me know if any further adjustments are needed.

**Pull request merged**
